import { Header } from "@/components/header";
import { EngineeringDiagram } from "@/components/engineering-diagram";
import { ProjectBrief } from "@/components/project-brief";
import { Arrow, Logo, SectionHeading } from "@/components/ui";

const services = [
  { title: "Dedicated engineering teams", description: "Good people, fully in your corner. Engineers who become part of your team, understand your product, and build with you for the long term.", tags: "Embedded teams · Flexible capacity", icon: "team" },
  { title: "Custom software development", description: "Software shaped around how your business actually works. Thoughtfully designed systems that solve the right problems and hold up over time.", tags: "Web applications · Business systems", icon: "code" },
  { title: "Product development & delivery", description: "Turn a promising idea into a product people use. From early discovery and an MVP to steady releases, with a clear path at every stage.", tags: "Discovery · MVPs · Product evolution", icon: "product" },
  { title: "Cloud & DevOps engineering", description: "A dependable foundation for your software. Infrastructure, delivery pipelines, and observability that make shipping simpler and growth manageable.", tags: "Cloud infrastructure · CI/CD · Reliability", icon: "cloud" },
  { title: "Technology consulting", description: "An experienced perspective when the next step isn’t obvious. Practical advice on architecture, technical decisions, and the road ahead.", tags: "Architecture · Technical strategy", icon: "consult" },
];

function ServiceIcon({ type }: { type: string }) {
  const paths: Record<string, string> = { team: "M8 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM2 20v-2a6 6 0 0 1 12 0v2m3-15a3 3 0 0 1 0 6m0 3a5 5 0 0 1 5 5v1", code: "m8 7-5 5 5 5m8-10 5 5-5 5m-3-14-2 18", product: "m12 3 9 5-9 5-9-5 9-5Zm-9 9 9 5 9-5M3 17l9 5 9-5", cloud: "M7 18a5 5 0 1 1 0-10 6 6 0 0 1 11-1 5.5 5.5 0 0 1 0 11M12 11v11m-3-8 3-3 3 3", consult: "M4 4h16v12H9l-5 4V4Zm4 5h8m-8 3h5" };
  return <svg width="26" height="26" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d={paths[type]} stroke="currentColor" strokeWidth="1.35" strokeLinecap="round" strokeLinejoin="round" /></svg>;
}

export default function Home() {
  return <><Header /><main id="main"><section className="hero" id="top"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> YOUR NEXT CHAPTER, WELL BUILT.</p><h1>Engineering for<br />what comes <span>next.</span></h1><p className="hero-description">We bring the people, thinking, and engineering to turn complex challenges into dependable software.</p><div className="hero-actions"><a href="#contact" className="button button-dark">Let’s build together <Arrow diagonal /></a><a href="#services" className="text-link">Explore our capabilities <Arrow /></a></div><p className="hero-note">From the first conversation to the next release.</p></div><EngineeringDiagram /></div><div className="container hero-bottom"><p>A practical partner.<br /><strong>Across your entire software journey.</strong></p><div className="journey"><span>Understand</span><span className="journey-line" /><span>Build</span><span className="journey-line" /><span>Improve</span></div></div></section>
  <section className="section services" id="services"><div className="container"><SectionHeading number="01" label="WHAT WE DO" title={"The right expertise.\nRight where you need it."}>A team to extend yours, a product to bring to life, or a system to get right. We meet you where you are.</SectionHeading><div className="services-grid">{services.map((service, index) => <article className="service" key={service.title}><div className="service-top"><ServiceIcon type={service.icon} /><span>0{index + 1}</span></div><h3>{service.title}</h3><p>{service.description}</p><div className="service-tags">{service.tags}</div></article>)}<div className="service service-prompt"><p className="eyebrow">NOT SURE WHERE TO START?</p><h3>Let’s find the<br />right way forward.</h3><a href="#contact" className="text-link">Tell us what you have in mind <Arrow diagonal /></a></div></div></div></section>
  <section className="section approach" id="approach"><div className="container approach-grid"><div><p className="eyebrow"><span>02</span> / OUR APPROACH</p><h2>Good software starts<br />with understanding.</h2><p className="approach-intro">Before we write a line of code, we listen. To your goals, your constraints, and the people who will use what we build.</p><p className="approach-detail">Then we work alongside you, making considered decisions and delivering in useful increments. Clear communication, shared ownership, and engineering that earns your confidence.</p><a href="#contact" className="text-link">Get to know your next engineering partner <Arrow diagonal /></a></div><div className="principles">{[{ number: "01", title: "Your goals, our starting point", text: "We understand the business behind the brief, so every technical decision has a purpose." }, { number: "02", title: "Part of your team", text: "Direct conversations, visible progress, and people who take ownership of the outcome." }, { number: "03", title: "Built for the long run", text: "Maintainable code, thoughtful architecture, and a foundation your team can keep building on." }].map(item => <article key={item.number} className="principle"><span>{item.number}</span><div><h3>{item.title}</h3><p>{item.text}</p></div></article>)}</div></div></section>
  <section className="section expertise" id="expertise"><div className="container"><SectionHeading number="03" label="WHERE WE GO DEEP" title={"Real challenges.\nThoughtful solutions."}>Our expertise spans the products people use and the systems that keep businesses running.</SectionHeading><div className="expertise-grid"><article className="expertise-item"><div className="expertise-art platform-art" aria-hidden="true"><div className="mock-sidebar"><i /><i /><i /><i /></div><div className="mock-platform"><div className="mock-top"><span>Operations overview</span><i /></div><div className="mock-stats"><div /><div /><div /></div><div className="mock-chart"><svg viewBox="0 0 300 85" fill="none"><path d="M0 70h300M0 40h300M0 10h300" stroke="#e1e6e1" /><path d="m0 65 35-10 30 8 35-30 30 8 35-22 30 6 35-19 35 4" stroke="#648779" strokeWidth="2.5" /></svg></div><div className="mock-rows"><span /><span /><span /></div></div><span className="art-label">SYSTEMS THAT MAKE WORK FLOW</span></div><p className="expertise-category">BUSINESS SYSTEMS</p><h3>Less friction. Better operations.</h3><p>Connected platforms that replace fragmented workflows and give your team a clearer picture.</p><div className="expertise-tags"><span>Internal tools</span><span>Integrations</span><span>Automation</span></div></article><article className="expertise-item"><div className="expertise-art product-art" aria-hidden="true"><div className="mock-browser"><div className="browser-bar"><i /><i /><i /><span>Workspace</span></div><div className="product-content"><div className="product-greeting">A little more clarity.<br /><strong>A lot more possibility.</strong></div><div className="product-blocks"><div><span className="block-icon">↗</span><span>Your next step</span><i /></div><div><span className="block-icon">◎</span><span>The bigger picture</span><i /></div></div></div></div><span className="art-label">PRODUCTS WITH PEOPLE AT THE CENTER</span></div><p className="expertise-category">DIGITAL PRODUCTS</p><h3>From an idea to everyday value.</h3><p>Useful, intuitive products with the engineering behind them to grow from first launch to what’s next.</p><div className="expertise-tags"><span>SaaS platforms</span><span>Web applications</span><span>MVPs</span></div></article></div><div className="technology-row"><p>Good tools. Chosen for the job.</p><div><span>React</span><span>Next.js</span><span>Node.js</span><span>Python</span><span>PostgreSQL</span><span>AWS</span><span>Docker</span></div></div></div></section>
  <section className="contact-section" id="contact"><div className="container contact-inner"><div><p className="eyebrow"><span className="status-dot" /> LET’S MAKE PROGRESS</p><h2>What are you<br />building next?</h2><p>A new idea. A growing team. A challenge worth solving.<br />Let’s figure out the next step together.</p></div><div className="contact-action"><ProjectBrief /><span>A simple brief. A clearer starting point.</span></div></div></section></main><footer className="footer"><div className="container"><div className="footer-top"><div><Logo /><p>Thoughtful teams. Dependable software.</p></div><nav aria-label="Footer navigation"><a href="#services">Capabilities</a><a href="#approach">Our approach</a><a href="#expertise">Expertise</a><a href="#contact">Start a conversation <Arrow diagonal /></a></nav></div><div className="footer-bottom"><p>© {new Date().getFullYear()} Fieldwork. All rights reserved.</p><p>Built with care. Built to last.</p><a href="#top">Back to top ↑</a></div></div></footer></>;
}
